compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU     # Multi-GPU mode
fp16: true                     # Set according to your amp configuration
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2                # 2 threads in this example (I.e. 2 GPU's)
gpu_ids: "4,5"                  # Which GPU ID's to be used for training
